version: '3.4'

services:
  mysql:
    container_name: bella_db
    image: mysql:8.0.20
    platform: linux/x86_64
    command: '--default-authentication-plugin=mysql_native_password'
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: bella
      MYSQL_ROOT_PASSWORD: root
      TZ: UTC
    volumes:
      - ./.docker/bella_db/data:/var/lib/mysql
