version: '3.7'

networks:
  bella-net:
    name: bella-net
    driver: bridge

services:
  mysql_game:
    container_name: game_db
    image: mysql:8.0-oracle
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${GAME_DB_DATABASE}
      MYSQL_USER: ${GAME_DB_USERNAME}
      MYSQL_PASSWORD: ${GAME_DB_PASSWORD}
    ports:
      - ${GAME_DB_PORT}:3306
    volumes:
      - ./.docker/game_db:/var/lib/mysql
    extra_hosts:
      - "host.docker.internal:host-gateway"

  redis:
    container_name: bella_redis
    image: redis:6
    ports:
      - '6379:6379'

# FLARUM

  flarum_db:
    image: mariadb:10.5
    container_name: flarum_db
    command:
      - "mysqld"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
    volumes:
      - ./.docker/flarum_db:/var/lib/mysql
    environment:
      TZ: ${TZ}
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: ${FLARUM_DB_DATABASE}
      MYSQL_USER: ${FLARUM_DB_USER}
      MYSQL_PASSWORD: ${FLARUM_DB_PASSWORD}
    ports:
      - ${FLARUM_DB_PORT}:3306
    networks:
      - bella-net
    restart: always
