name: Node.js CI

on: [workflow_dispatch]

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.10.0'
          cache: 'yarn'
      - run: yarn install

  format:
    needs: install
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.10.0'
          cache: 'yarn'
      - run: yarn run format

  lint:
    needs: [install, format]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
           node-version: '16.10.0'
           cache: 'yarn'
      - run: yarn run lint

  build:
    needs: [install, format, lint]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.10.0'
          cache: 'yarn'
      - run: yarn build
